### ISSUE TITLE
info command

### ISSUE THREAD

**Issue by bmankowitz** [bmankowitz/FileSystems#4]
info command works: 5 points

**Comment by shuyttr** [comment]
_info_ function
Description: prints out information about the following fields in both hex and base 10:
-  BPB_BytesPerSec
-  BPB_SecPerClus 
-  BPB_RsvdSecCnt 
-  BPB_NumFATS
-  BPB_FATSz32

**Comment by shuyttr** [comment]
Taking care of this currently
