### ISSUE TITLE
stat command started

### ISSUE THREAD

**Issue by bmankowitz** [bmankowitz/FileSystems#6]
stat command started: 2 points

**Comment by shuyttr** [comment]
_stat <FILE_NAME/DIR_NAME>_
Description: prints the sizeof the file or directory name, the attributes of the file or directory name, and the first cluster number of the file or directory name if it is in the present working directory.  Return an error if FILE_NAME/DIR_NAME does not exist. (Note: The size of a directory will always be zero.)
